export const flags = {
	Adelaide: require("./Adelaide.jpg"),
	Brisbane: require("./Brisbane.jpg"),
	Carlton: require("./Carlton.jpg"),
	Collingwood: require("./Collingwood.jpg"),
	Essendon: require("./Essendon.jpg"),
	Fremantle: require("./Fremantle.jpg"),
	Geelong: require("./Geelong.jpg"),
	"Gold Coast": require("./GoldCoast.jpg"),
	"GWS Giants": require("./GWSGiants.jpg"),
	Hawthorn: require("./Hawthorn.jpg"),
	Melbourne: require("./Melbourne.jpg"),
	"North Melbourne": require("./NorthMelbourne.jpg"),
	"Port Adelaide": require("./PortAdelaide.jpg"),
	Richmond: require("./Richmond.jpg"),
	"St Kilda": require("./StKilda.jpg"),
	Sydney: require("./Sydney.jpg"),
	"West Coast": require("./WestCoast.jpg"),
	"Western Bulldogs": require("./WesternBulldogs.jpg")
}
